### ISSUE TITLE
perspective not found

### ISSUE THREAD

**Issue by sultanmalik04** [insidesherpa/bank-mergeCoTechTask2#296] opened 2020-09-06 12:53 UTC
```
C:/Users/DELL/Desktop/JPMC-tech-task-2-PY3/src/Graph.tsx
Type error: Cannot find module '@jpmorganchase/perspective'.  TS2307

    1 | import React, { Component } from 'react';
  > 2 | import { Table } from '@jpmorganchase/perspective';
      |                       ^
    3 | import { ServerRespond } from './DataStreamer';
    4 | import './Graph.css';
 ```

**Comment by khelali** [comment] 2020-09-08 19:59
How did you solve this?

**Comment by sultanmalik04** [comment] 2020-09-09 08:28
I have done all the things systematically but while running "npm install"
get the attached outcome....
can you help solving this?

**Comment by khelali** [comment] 2020-09-09 08:35
Turns out, you just have to download the node_modules folder they have provided at the end of their troubleshooting slides.
https://drive.google.com/file/d/1amF7C-4mRZCi3Ab5xuH0XCRQubp4aa_t/view
Also, the problem has already been posted and solved at least once in this forum.

**Comment by khelali** [comment] 2020-09-09 08:35
Once downloaded and expanded, you should replace the folder you already have in the task folder by this one. It will work instantly!

**Comment by sultanmalik04** [comment] 2020-09-09 10:35
didn't worked.....

**Comment by khelali** [comment] 2020-09-09 11:16
If you're losing hope, one radical way to solve this would be to delete whatever you have now and clone the repository again and restart from scratch.. you might have messed up something while fixing npm install issues. I did it and it worked.

**Comment by AmberSRP** [comment] 2020-09-12 17:58
hi,
let me know if you're still having problem because i have a solution.
have a nice day.

**Comment by sultanmalik04** [comment] 2020-09-16 05:51
Yes i am starting again from i messed everything during setup...😅
Can you help me ...?

**Comment by sultanmalik04** [comment] 2020-09-16 05:53
Yes i messed everything during setup...
I am starting again from scratch can you help me....??

**Comment by AmberSRP** [comment] 2020-09-16 06:11
It will be my pleasure!
So Could you tell me what steps have you done until now, so I can understand your situation?

**Comment by sultanmalik04** [comment] 2020-09-16 06:19
my server is running successfully, now i have to setup node, npm, and nvm....

**Comment by AmberSRP** [comment] 2020-09-16 06:25
Node version?

**Comment by sultanmalik04** [comment] 2020-09-16 06:35
I have to install v11.0.0 ...
but before i have to setup nvm ...how should I do this...

**Comment by AmberSRP** [comment] 2020-09-16 06:51
https://www.npmjs.com/get-npm
https://codeburst.io/nvm-for-windows-how-to-install-and-use-13b7a4209791
Use second one for step by step procedure for installing Node Version Manager.

**Comment by AmberSRP** [comment] 2020-09-16 06:55
https://github.com/coreybutler/nvm-windows
You can download NVM from here.

**Comment by sultanmalik04** [comment] 2020-09-16 06:55
DONE...

**Comment by sultanmalik04** [comment] 2020-09-16 06:55
Now i have to setup node-gyp...

**Comment by sultanmalik04** [comment] 2020-09-16 06:59
i have installed visual studio build tools ... now i don't know the next step...

**Comment by AmberSRP** [comment] 2020-09-16 07:00
Now,
https://nodejs.org/dist/v11.14.0/node-v11.14.0-x86.msi
Install this (Node + NPM)

**Comment by AmberSRP** [comment] 2020-09-16 07:01
This is for 32- bit. If you have 64 then text me

**Comment by AmberSRP** [comment] 2020-09-16 07:02
https://nodejs.org/dist/v11.14.0/node-v11.14.0-x64.msi
This for 64-bit

**Comment by sultanmalik04** [comment] 2020-09-16 07:09
i have installed nvm and npm....
![](https://drive.google.com/file/d/1as4ysy0isiMZTExoOwtoveSzs111RK1t/view?usp=sharing)

**Comment by sultanmalik04** [comment] 2020-09-16 07:12
jpmorgan1.png
<https://drive.google.com/file/d/1as4ysy0isiMZTExoOwtoveSzs111RK1t/view?usp=drivesdk>

**Comment by AmberSRP** [comment] 2020-09-16 07:17
So you have 64-bit! Nice!
Now try npm install, and then npm start.
Text me if it works.

**Comment by sultanmalik04** [comment] 2020-09-16 07:26
thank you very much....
WORKED...

**Comment by AmberSRP** [comment] 2020-09-16 07:29
Well, now you can close this, as the issue is solved.
Best of luck for your project.

**Closed as completed** 2020-09-16 07:30 UTC
